import { promises as fs } from "node:fs";
import path from "node:path";
import { getWorkspacePaths, readJsonl } from "./config.js";

export interface McpResourceInfo {
  uri: string;
  name: string;
  mimeType: string;
  description: string;
}

export const mcpResources: McpResourceInfo[] = [
  { uri: "soturail://repo-map", name: "Heuristic Repo Map", mimeType: "application/json", description: "Stable repository map generated by soturail index." },
  { uri: "soturail://tree", name: "Repository Tree", mimeType: "text/plain", description: "Stable tree output generated by soturail index." },
  { uri: "soturail://rules", name: "Rules", mimeType: "text/yaml", description: "Extracted local rules." },
  { uri: "soturail://approved-memory", name: "Approved Memory", mimeType: "application/jsonl", description: "Approved local memory records." },
  { uri: "soturail://self-report", name: "Self Dogfood Report", mimeType: "text/markdown", description: "Latest self-dogfooding report." },
  { uri: "soturail://benchmarks/latest", name: "Latest Benchmarks", mimeType: "application/json", description: "Latest benchmark JSON results." },
  { uri: "soturail://roadmap", name: "Roadmap", mimeType: "text/markdown", description: "Project roadmap." }
];

export async function listMcpResources(): Promise<McpResourceInfo[]> {
  return mcpResources;
}

export async function readMcpResource(uri: string, root = process.cwd()): Promise<{ uri: string; mimeType: string; text: string }> {
  const paths = getWorkspacePaths(root);
  const stableFirstNotice = "SotuRail resource: stable project content first; dynamic metadata appears last when present.\n\n";
  switch (uri) {
    case "soturail://repo-map":
      return resource(uri, "application/json", stableFirstNotice + await readOptional(path.join(paths.indexesDir, "repo-map.json"), "{}"));
    case "soturail://tree":
      return resource(uri, "text/plain", stableFirstNotice + await readOptional(path.join(paths.indexesDir, "tree.txt"), "No tree found. Run soturail index."));
    case "soturail://rules":
      return resource(uri, "text/yaml", stableFirstNotice + await readOptional(paths.rulesFile, "No rules found."));
    case "soturail://approved-memory": {
      const approved = await readJsonl<unknown>(paths.memoryApprovedFile);
      return resource(uri, "application/jsonl", stableFirstNotice + approved.map((item) => JSON.stringify(item)).join("\n"));
    }
    case "soturail://self-report":
      return resource(uri, "text/markdown", await readOptional(path.join(paths.workspace, "reports", "self-dogfood.md"), "No self report found."));
    case "soturail://benchmarks/latest":
      return resource(uri, "application/json", await readOptional(path.join(root, "benchmarks", "results", "latest.json"), "{}"));
    case "soturail://roadmap":
      return resource(uri, "text/markdown", await readOptional(path.join(root, "ROADMAP.md"), "No roadmap found."));
    default:
      throw new Error(`Unknown MCP resource: ${uri}`);
  }
}

function resource(uri: string, mimeType: string, text: string): { uri: string; mimeType: string; text: string } {
  return { uri, mimeType, text };
}

async function readOptional(filePath: string, fallback: string): Promise<string> {
  return fs.readFile(filePath, "utf8").catch(() => fallback);
}
