import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { ensureWorkspace, getWorkspacePaths } from "./config.js";
import { getHostAdapter, isHostId, type SkillProjection } from "./host-adapters.js";
import { pathExists } from "./rail-utils.js";
import { redactText } from "./report-redaction.js";
import { loadSkillCatalog, PROJECTION_MARKER, renderSkillMarkdown, type SkillModel } from "./skill-model.js";
import { WorkspaceGuard } from "./workspace-guard.js";
import { type SkillTarget } from "./skill-schema.js";
import { readSkills } from "./skill-store.js";
import { validateSkills } from "./skill-validator.js";

export async function exportSkills(target: SkillTarget, root = process.cwd()): Promise<string> {
  await ensureWorkspace(root);
  const validation = await validateSkills(root);
  if (!validation.ok) {
    throw new Error("Cannot export invalid skills. Run soturail skills validate for details.");
  }
  const skills = await readSkills(root);
  const paths = getWorkspacePaths(root);
  const targetDir = path.join(paths.skillExportsDir, target);
  await fs.mkdir(targetDir, { recursive: true });

  const written: string[] = [];
  for (const skill of skills) {
    const filePath = path.join(targetDir, `${skill.metadata.id}.md`);
    await fs.writeFile(filePath, renderTargetSkill(target, skill.metadata.id, skill.markdown), "utf8");
    written.push(path.normalize(path.relative(root, filePath)));
  }

  const indexPath = path.join(targetDir, "index.md");
  await fs.writeFile(indexPath, renderExportIndex(target, skills.map((skill) => skill.metadata.id)), "utf8");
  written.push(path.normalize(path.relative(root, indexPath)));
  return `Exported ${skills.length} skill(s) for ${target}:\n${written.join("\n")}\n`;
}

export async function packSkills(format: "json" | "markdown", root = process.cwd()): Promise<string> {
  await ensureWorkspace(root);
  const skills = await readSkills(root);
  const paths = getWorkspacePaths(root);
  const filePath = path.join(paths.skillExportsDir, `skills-pack.${format === "json" ? "json" : "md"}`);
  const payload = format === "json"
    ? `${JSON.stringify(skills.map((skill) => ({ metadata: skill.metadata, markdown: skill.markdown })), null, 2)}\n`
    : skills.map((skill) => renderTargetSkill("generic", skill.metadata.id, skill.markdown)).join("\n---\n");
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, payload, "utf8");
  return `Skill pack written: ${path.normalize(path.relative(root, filePath))}\n`;
}

function renderTargetSkill(target: SkillTarget, id: string, markdown: string): string {
  const header = [
    `# SotuRail Skill: ${id}`,
    "",
    `Target: ${target}`,
    "Generated by SotuRail Skill Rail as an independent local-first export.",
    "",
    "Safety constraints:",
    "- Do not run destructive shell commands.",
    "- Do not exfiltrate secrets.",
    "- Ask for human approval before remote writes or destructive actions.",
    "- Treat this export as project-local guidance, not a marketplace install.",
    ""
  ];
  const targetNote: Record<SkillTarget, string> = {
    claude: "Claude usage: place this in a reviewed skill/rules location supported by your installed Claude Code version.",
    codex: "Codex usage: include this in AGENTS.md or project rules after review.",
    gemini: "Gemini usage: include this as concise project guidance after review.",
    cursor: "Cursor usage: include this in .cursor/rules after review.",
    generic: "Generic usage: portable Markdown guidance for local AI agent workflows."
  };
  return `${header.join("\n")}${targetNote[target]}\n\n${markdown.trim()}\n`;
}

function renderExportIndex(target: SkillTarget, ids: string[]): string {
  return [
    `# SotuRail ${target} Skill Export`,
    "",
    "Review all generated files before enabling them in an agent host.",
    "",
    ...ids.map((id) => `- [${id}](./${id}.md)`),
    ""
  ].join("\n");
}

export interface PortableSkillExport {
  schemaVersion: "soturail.skill-export.v2";
  layout: "agent-skills";
  outDir: string;
  host: { id: string; requested: string; verification: SkillProjection["verification"]; projectDir: string | null; limitations: string[] };
  skills: Array<{ name: string; source: SkillModel["source"]; files: Array<{ path: string; sha256: string }> }>;
  skipped: Array<{ name: string; reason: string }>;
}

export interface PortableExportOptions {
  /** Host adapter to project for; unknown hosts use the generic adapter. */
  host?: string;
  /** Write into the host's native project skills directory instead of .soturail/exports. */
  install?: boolean;
  outDir?: string;
  bundledDir?: string;
}

// Legacy v1.5 pack artifacts that become on-demand references in a portable export.
const LEGACY_REFERENCE_FILES = ["safety.md", "glossary.md", "patterns.md", "cheatsheet.md"];
const LEGACY_REFERENCE_DIRS = ["topics", "examples"];

/**
 * Write every valid skill as a portable Agent Skills directory
 * (<name>/SKILL.md + references/scripts/assets). Sources are never rewritten;
 * v1.5 packs are rendered side by side with generated frontmatter.
 */
export async function exportPortableSkills(root = process.cwd(), options: PortableExportOptions = {}): Promise<PortableSkillExport> {
  await ensureWorkspace(root);
  const guard = new WorkspaceGuard(root);
  const requested = options.host ?? "generic";
  const adapter = getHostAdapter(requested);
  const projectDir = adapter.skills.projectDir ?? ".agents/skills";
  const outDir = options.install
    ? await guard.resolveProjectPath(projectDir, { mustExist: false })
    : options.outDir
      ? await guard.resolveProjectPath(options.outDir, { mustExist: false })
      : path.join(getWorkspacePaths(root).skillExportsDir, "portable", ...(options.host ? [adapter.id] : []));
  // Outside .soturail/ only directories carrying our marker may be replaced.
  const managedOnly = !await guard.isInsideWorkspace(outDir);
  const catalog = await loadSkillCatalog(root, options.bundledDir ? { bundledDir: options.bundledDir } : {});
  const result: PortableSkillExport = {
    schemaVersion: "soturail.skill-export.v2",
    layout: "agent-skills",
    outDir: await guard.projectRelative(outDir),
    host: { id: adapter.id, requested, verification: isHostId(requested) ? adapter.skills.verification : "generic-fallback", projectDir: adapter.skills.projectDir, limitations: [...adapter.skills.limitations] },
    skills: [],
    skipped: []
  };
  for (const skill of catalog.skills) {
    const errors = catalog.issues.filter((issue) => issue.skill === skill.name && issue.severity === "error");
    if (errors.length) {
      result.skipped.push({ name: skill.name, reason: errors.map((issue) => issue.code).join(",") });
      continue;
    }
    const files = await portableFiles(skill);
    const leaked = files.find((file) => redactText(file.content).redactions.length > 0);
    if (leaked) {
      result.skipped.push({ name: skill.name, reason: `secret_like_content:${leaked.path}` });
      continue;
    }
    const skillDir = path.join(outDir, skill.name);
    if (managedOnly && await pathExists(skillDir) && !await pathExists(path.join(skillDir, PROJECTION_MARKER))) {
      result.skipped.push({ name: skill.name, reason: "unmanaged_existing_dir" });
      continue;
    }
    await fs.rm(skillDir, { recursive: true, force: true });
    const written: Array<{ path: string; sha256: string }> = [];
    for (const file of files) {
      const target = path.join(skillDir, file.path);
      guard.assertInside(skillDir, path.resolve(target));
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, file.content, "utf8");
      written.push({ path: file.path, sha256: createHash("sha256").update(file.content).digest("hex") });
    }
    await fs.mkdir(skillDir, { recursive: true });
    await fs.writeFile(path.join(skillDir, PROJECTION_MARKER), `${JSON.stringify({ schemaVersion: "soturail.skill-projection.v1", host: adapter.id, source: skill.source, sourceDigest: skill.digest, files: written }, null, 2)}\n`, "utf8");
    result.skills.push({ name: skill.name, source: skill.source, files: written });
  }
  await fs.mkdir(outDir, { recursive: true });
  // Host skill directories hold only skill folders; the manifest stays in SotuRail exports.
  if (!options.install) await fs.writeFile(path.join(outDir, "soturail-export.json"), `${JSON.stringify(result, null, 2)}\n`, "utf8");
  return result;
}


async function portableFiles(skill: SkillModel): Promise<Array<{ path: string; content: string }>> {
  if (skill.source !== "legacy-pack") {
    const files = [{ path: "SKILL.md", content: await fs.readFile(path.join(skill.dir, "SKILL.md"), "utf8") }];
    for (const resource of skill.resources) files.push({ path: resource, content: await fs.readFile(path.join(skill.dir, resource), "utf8") });
    return files;
  }
  const references: Array<{ path: string; content: string }> = [];
  for (const name of LEGACY_REFERENCE_FILES) {
    const content = await fs.readFile(path.join(skill.dir, name), "utf8").catch(() => null);
    if (content !== null) references.push({ path: `references/${name}`, content });
  }
  for (const dir of LEGACY_REFERENCE_DIRS) {
    for (const file of await listFilesRecursive(path.join(skill.dir, dir))) {
      references.push({ path: `references/${dir}/${file}`, content: await fs.readFile(path.join(skill.dir, dir, file), "utf8") });
    }
  }
  const frontmatter = { ...skill.frontmatter, metadata: { ...skill.frontmatter.metadata, "soturail-source": "legacy-pack", "soturail-source-digest": skill.digest } };
  const note = references.length ? "\n\n## References\n\nMigrated v1.5 pack material is under `references/`; load it only when needed.\n" : "";
  return [{ path: "SKILL.md", content: renderSkillMarkdown(frontmatter, `${skill.body.trim()}${note}`) }, ...references];
}

async function listFilesRecursive(dir: string, prefix = ""): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true }).catch(() => [])) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) files.push(...await listFilesRecursive(path.join(dir, entry.name), relative));
    else if (entry.isFile()) files.push(relative);
  }
  return files.sort();
}
