import { promises as fs } from "node:fs";
import path from "node:path";
import { ensureWorkspace, getWorkspacePaths } from "./config.js";
import { type SkillTarget } from "./skill-schema.js";
import { readSkills } from "./skill-store.js";
import { validateSkills } from "./skill-validator.js";

export async function exportSkills(target: SkillTarget, root = process.cwd()): Promise<string> {
  await ensureWorkspace(root);
  const validation = await validateSkills(root);
  if (!validation.ok) {
    throw new Error("Cannot export invalid skills. Run soturail skills validate for details.");
  }
  const skills = await readSkills(root);
  const paths = getWorkspacePaths(root);
  const targetDir = path.join(paths.skillExportsDir, target);
  await fs.mkdir(targetDir, { recursive: true });

  const written: string[] = [];
  for (const skill of skills) {
    const filePath = path.join(targetDir, `${skill.metadata.id}.md`);
    await fs.writeFile(filePath, renderTargetSkill(target, skill.metadata.id, skill.markdown), "utf8");
    written.push(path.normalize(path.relative(root, filePath)));
  }

  const indexPath = path.join(targetDir, "index.md");
  await fs.writeFile(indexPath, renderExportIndex(target, skills.map((skill) => skill.metadata.id)), "utf8");
  written.push(path.normalize(path.relative(root, indexPath)));
  return `Exported ${skills.length} skill(s) for ${target}:\n${written.join("\n")}\n`;
}

export async function packSkills(format: "json" | "markdown", root = process.cwd()): Promise<string> {
  await ensureWorkspace(root);
  const skills = await readSkills(root);
  const paths = getWorkspacePaths(root);
  const filePath = path.join(paths.skillExportsDir, `skills-pack.${format === "json" ? "json" : "md"}`);
  const payload = format === "json"
    ? `${JSON.stringify(skills.map((skill) => ({ metadata: skill.metadata, markdown: skill.markdown })), null, 2)}\n`
    : skills.map((skill) => renderTargetSkill("generic", skill.metadata.id, skill.markdown)).join("\n---\n");
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, payload, "utf8");
  return `Skill pack written: ${path.normalize(path.relative(root, filePath))}\n`;
}

function renderTargetSkill(target: SkillTarget, id: string, markdown: string): string {
  const header = [
    `# SotuRail Skill: ${id}`,
    "",
    `Target: ${target}`,
    "Generated by SotuRail Skill Rail as an independent local-first export.",
    "",
    "Safety constraints:",
    "- Do not run destructive shell commands.",
    "- Do not exfiltrate secrets.",
    "- Ask for human approval before remote writes or destructive actions.",
    "- Treat this export as project-local guidance, not a marketplace install.",
    ""
  ];
  const targetNote: Record<SkillTarget, string> = {
    claude: "Claude usage: place this in a reviewed skill/rules location supported by your installed Claude Code version.",
    codex: "Codex usage: include this in AGENTS.md or project rules after review.",
    gemini: "Gemini usage: include this as concise project guidance after review.",
    cursor: "Cursor usage: include this in .cursor/rules after review.",
    generic: "Generic usage: portable Markdown guidance for local AI agent workflows."
  };
  return `${header.join("\n")}${targetNote[target]}\n\n${markdown.trim()}\n`;
}

function renderExportIndex(target: SkillTarget, ids: string[]): string {
  return [
    `# SotuRail ${target} Skill Export`,
    "",
    "Review all generated files before enabling them in an agent host.",
    "",
    ...ids.map((id) => `- [${id}](./${id}.md)`),
    ""
  ].join("\n");
}
