#!/usr/bin/env node
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, "..");
const packageJsonPath = path.join(root, "package.json");
const versionPath = path.join(root, "src", "core", "version.ts");

const packageJson = JSON.parse(await fs.readFile(packageJsonPath, "utf8"));
const version = packageJson.version;

if (typeof version !== "string" || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`package.json has an invalid version: ${String(version)}`);
}

const contents = `// Generated by scripts/sync-version.mjs from package.json. Do not edit manually.
export const SOTURAIL_VERSION = ${JSON.stringify(version)};
`;

await fs.writeFile(versionPath, contents, "utf8");
